package com.panorama.common;
/**/
/**
 * This class was automatically generated by the data modeler tool.
 */

public class Account implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("customerNumber")
   private java.lang.String customerNumber;
   @org.kie.api.definition.type.Label("status")
   private java.lang.String status;
   @org.kie.api.definition.type.Label("label")
   private java.lang.String label;
   @org.kie.api.definition.type.Label("balance")
   private com.panorama.common.Balance balance;
   @org.kie.api.definition.type.Label("type")
   private java.lang.String type;
   @org.kie.api.definition.type.Label("accountRoutingAsString")
   private java.lang.String accountRoutingAsString;
   @org.kie.api.definition.type.Label("accountRulesAsString")
   private java.lang.String accountRulesAsString;
   @org.kie.api.definition.type.Label("id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label("bank_id")
   private java.lang.String bank_id;
   @org.kie.api.definition.type.Label("account_rules")
   private java.util.List<com.panorama.common.Account_rules> account_rules;

   @org.kie.api.definition.type.Label(value = "account_routing")
   private java.util.List<com.panorama.common.AccountRouting> account_routing;

   public Account()
   {
   }

   public java.lang.String getCustomerNumber()
   {
      return this.customerNumber;
   }

   public void setCustomerNumber(java.lang.String customerNumber)
   {
      this.customerNumber = customerNumber;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String getLabel()
   {
      return this.label;
   }

   public void setLabel(java.lang.String label)
   {
      this.label = label;
   }

   public com.panorama.common.Balance getBalance()
   {
      return this.balance;
   }

   public void setBalance(com.panorama.common.Balance balance)
   {
      this.balance = balance;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getAccountRoutingAsString()
   {
      return this.accountRoutingAsString;
   }

   public void setAccountRoutingAsString(
         java.lang.String accountRoutingAsString)
   {
      this.accountRoutingAsString = accountRoutingAsString;
   }

   public java.lang.String getAccountRulesAsString()
   {
      return this.accountRulesAsString;
   }

   public void setAccountRulesAsString(java.lang.String accountRulesAsString)
   {
      this.accountRulesAsString = accountRulesAsString;
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getBank_id()
   {
      return this.bank_id;
   }

   public void setBank_id(java.lang.String bank_id)
   {
      this.bank_id = bank_id;
   }

   public java.util.List<com.panorama.common.Account_rules> getAccount_rules()
   {
      return this.account_rules;
   }

   public void setAccount_rules(
         java.util.List<com.panorama.common.Account_rules> account_rules)
   {
      this.account_rules = account_rules;
   }

   public java.util.List<com.panorama.common.AccountRouting> getAccount_routing()
   {
      return this.account_routing;
   }

   public void setAccount_routing(
         java.util.List<com.panorama.common.AccountRouting> account_routing)
   {
      this.account_routing = account_routing;
   }

   public Account(java.lang.String customerNumber, java.lang.String status,
         java.lang.String label, com.panorama.common.Balance balance,
         java.lang.String type, java.lang.String accountRoutingAsString,
         java.lang.String accountRulesAsString, java.lang.String id,
         java.lang.String bank_id,
         java.util.List<com.panorama.common.Account_rules> account_rules,
         java.util.List<com.panorama.common.AccountRouting> account_routing)
   {
      this.customerNumber = customerNumber;
      this.status = status;
      this.label = label;
      this.balance = balance;
      this.type = type;
      this.accountRoutingAsString = accountRoutingAsString;
      this.accountRulesAsString = accountRulesAsString;
      this.id = id;
      this.bank_id = bank_id;
      this.account_rules = account_rules;
      this.account_routing = account_routing;
   }

}