package com.panorama.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Account_rules implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "scheme")
   private java.lang.String scheme;
   @org.kie.api.definition.type.Label(value = "value")
   private java.lang.String value;

   public Account_rules()
   {
   }

   public java.lang.String getScheme()
   {
      return this.scheme;
   }

   public void setScheme(java.lang.String scheme)
   {
      this.scheme = scheme;
   }

   public java.lang.String getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }

   public Account_rules(java.lang.String scheme, java.lang.String value)
   {
      this.scheme = scheme;
      this.value = value;
   }

}