package com.panorama.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Action implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("actionNumber")
   private java.lang.String actionNumber;
   @org.kie.api.definition.type.Label("actionTime")
   private java.lang.String actionTime;
   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label("actionCode")
   private java.lang.String actionCode;
   @org.kie.api.definition.type.Label("globalId")
   private java.lang.String globalId;
   @org.kie.api.definition.type.Label("narrative")
   private java.lang.String narrative;
   @org.kie.api.definition.type.Label("statusFlag")
   private java.lang.String statusFlag;
   @org.kie.api.definition.type.Label("assignTo")
   private com.panorama.common.AssignTo assignTo;
   @org.kie.api.definition.type.Label("level")
   private com.panorama.common.CodeValue level;
   @org.kie.api.definition.type.Label("type")
   private com.panorama.common.CodeValue type;
   @org.kie.api.definition.type.Label("taskNumber")
   private java.lang.String taskNumber;

   @org.kie.api.definition.type.Label(value = "paramList")
   private java.util.List<com.panorama.common.KeyValueParam> paramList;

   public Action()
   {
   }

   public java.lang.String getActionNumber()
   {
      return this.actionNumber;
   }

   public void setActionNumber(java.lang.String actionNumber)
   {
      this.actionNumber = actionNumber;
   }

   public java.lang.String getActionTime()
   {
      return this.actionTime;
   }

   public void setActionTime(java.lang.String actionTime)
   {
      this.actionTime = actionTime;
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getActionCode()
   {
      return this.actionCode;
   }

   public void setActionCode(java.lang.String actionCode)
   {
      this.actionCode = actionCode;
   }

   public java.lang.String getGlobalId()
   {
      return this.globalId;
   }

   public void setGlobalId(java.lang.String globalId)
   {
      this.globalId = globalId;
   }

   public java.lang.String getNarrative()
   {
      return this.narrative;
   }

   public void setNarrative(java.lang.String narrative)
   {
      this.narrative = narrative;
   }

   public java.lang.String getStatusFlag()
   {
      return this.statusFlag;
   }

   public void setStatusFlag(java.lang.String statusFlag)
   {
      this.statusFlag = statusFlag;
   }

   public com.panorama.common.AssignTo getAssignTo()
   {
      return this.assignTo;
   }

   public void setAssignTo(com.panorama.common.AssignTo assignTo)
   {
      this.assignTo = assignTo;
   }

   public com.panorama.common.CodeValue getLevel()
   {
      return this.level;
   }

   public void setLevel(com.panorama.common.CodeValue level)
   {
      this.level = level;
   }

   public com.panorama.common.CodeValue getType()
   {
      return this.type;
   }

   public void setType(com.panorama.common.CodeValue type)
   {
      this.type = type;
   }

   public java.lang.String getTaskNumber()
   {
      return this.taskNumber;
   }

   public void setTaskNumber(java.lang.String taskNumber)
   {
      this.taskNumber = taskNumber;
   }

   public java.util.List<com.panorama.common.KeyValueParam> getParamList()
   {
      return this.paramList;
   }

   public void setParamList(
         java.util.List<com.panorama.common.KeyValueParam> paramList)
   {
      this.paramList = paramList;
   }

   public Action(java.lang.String actionNumber, java.lang.String actionTime,
         java.lang.String ticketNumber, java.lang.String actionCode,
         java.lang.String globalId, java.lang.String narrative,
         java.lang.String statusFlag, com.panorama.common.AssignTo assignTo,
         com.panorama.common.CodeValue level,
         com.panorama.common.CodeValue type, java.lang.String taskNumber,
         java.util.List<com.panorama.common.KeyValueParam> paramList)
   {
      this.actionNumber = actionNumber;
      this.actionTime = actionTime;
      this.ticketNumber = ticketNumber;
      this.actionCode = actionCode;
      this.globalId = globalId;
      this.narrative = narrative;
      this.statusFlag = statusFlag;
      this.assignTo = assignTo;
      this.level = level;
      this.type = type;
      this.taskNumber = taskNumber;
      this.paramList = paramList;
   }

}