package com.panorama.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Attachment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "attachmentNumber")
   private java.lang.String attachmenNumber;
   @org.kie.api.definition.type.Label(value = "ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label(value = "filePath")
   private java.lang.String filePath;
   @org.kie.api.definition.type.Label(value = "fileName")
   private java.lang.String fileName;
   @org.kie.api.definition.type.Label(value = "fileSize")
   private java.lang.String fileSize;
   @org.kie.api.definition.type.Label(value = "docType")
   private java.lang.String docType;
   @org.kie.api.definition.type.Label(value = "docTypeDescription")
   private java.lang.String docTypeDescription;
   @org.kie.api.definition.type.Label(value = "archiveFlag")
   private java.lang.String archiveFlag;
   @org.kie.api.definition.type.Label(value = "audit")
   private com.panorama.common.Audit audit;

   public Attachment()
   {
   }

   public java.lang.String getAttachmenNumber()
   {
      return this.attachmenNumber;
   }

   public void setAttachmenNumber(java.lang.String attachmenNumber)
   {
      this.attachmenNumber = attachmenNumber;
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getFilePath()
   {
      return this.filePath;
   }

   public void setFilePath(java.lang.String filePath)
   {
      this.filePath = filePath;
   }

   public java.lang.String getFileName()
   {
      return this.fileName;
   }

   public void setFileName(java.lang.String fileName)
   {
      this.fileName = fileName;
   }

   public java.lang.String getFileSize()
   {
      return this.fileSize;
   }

   public void setFileSize(java.lang.String fileSize)
   {
      this.fileSize = fileSize;
   }

   public java.lang.String getDocType()
   {
      return this.docType;
   }

   public void setDocType(java.lang.String docType)
   {
      this.docType = docType;
   }

   public java.lang.String getDocTypeDescription()
   {
      return this.docTypeDescription;
   }

   public void setDocTypeDescription(java.lang.String docTypeDescription)
   {
      this.docTypeDescription = docTypeDescription;
   }

   public java.lang.String getArchiveFlag()
   {
      return this.archiveFlag;
   }

   public void setArchiveFlag(java.lang.String archiveFlag)
   {
      this.archiveFlag = archiveFlag;
   }

   public com.panorama.common.Audit getAudit()
   {
      return this.audit;
   }

   public void setAudit(com.panorama.common.Audit audit)
   {
      this.audit = audit;
   }

   public Attachment(java.lang.String attachmenNumber,
         java.lang.String ticketNumber, java.lang.String filePath,
         java.lang.String fileName, java.lang.String fileSize,
         java.lang.String docType, java.lang.String docTypeDescription,
         java.lang.String archiveFlag, com.panorama.common.Audit audit)
   {
      this.attachmenNumber = attachmenNumber;
      this.ticketNumber = ticketNumber;
      this.filePath = filePath;
      this.fileName = fileName;
      this.fileSize = fileSize;
      this.docType = docType;
      this.docTypeDescription = docTypeDescription;
      this.archiveFlag = archiveFlag;
      this.audit = audit;
   }

}