package com.panorama.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditLimit implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("currency")
   private java.lang.String currency;
   @org.kie.api.definition.type.Label("amount")
   private java.lang.String amount;

   public CreditLimit()
   {
   }

   public java.lang.String getCurrency()
   {
      return this.currency;
   }

   public void setCurrency(java.lang.String currency)
   {
      this.currency = currency;
   }

   public java.lang.String getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.String amount)
   {
      this.amount = amount;
   }

   public CreditLimit(java.lang.String currency, java.lang.String amount)
   {
      this.currency = currency;
      this.amount = amount;
   }

}