package com.panorama.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Entity implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "entityType")
   private java.lang.String entityType;
   @org.kie.api.definition.type.Label(value = "entityNumber")
   private java.lang.String entityNumber;

   public Entity()
   {
   }

   public java.lang.String getEntityType()
   {
      return this.entityType;
   }

   public void setEntityType(java.lang.String entityType)
   {
      this.entityType = entityType;
   }

   public java.lang.String getEntityNumber()
   {
      return this.entityNumber;
   }

   public void setEntityNumber(java.lang.String entityNumber)
   {
      this.entityNumber = entityNumber;
   }

   public Entity(java.lang.String entityType, java.lang.String entityNumber)
   {
      this.entityType = entityType;
      this.entityNumber = entityNumber;
   }

}