package com.panorama.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Image implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label(value = "label")
   private java.lang.String label;
   @org.kie.api.definition.type.Label(value = "URL")
   private java.lang.String URL;
   @org.kie.api.definition.type.Label(value = "date")
   private java.lang.String date;
   @org.kie.api.definition.type.Label(value = "user")
   private com.panorama.common.User user;

   public Image()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getLabel()
   {
      return this.label;
   }

   public void setLabel(java.lang.String label)
   {
      this.label = label;
   }

   public java.lang.String getURL()
   {
      return this.URL;
   }

   public void setURL(java.lang.String URL)
   {
      this.URL = URL;
   }

   public java.lang.String getDate()
   {
      return this.date;
   }

   public void setDate(java.lang.String date)
   {
      this.date = date;
   }

   public com.panorama.common.User getUser()
   {
      return this.user;
   }

   public void setUser(com.panorama.common.User user)
   {
      this.user = user;
   }

   public Image(java.lang.String id, java.lang.String label,
         java.lang.String URL, java.lang.String date,
         com.panorama.common.User user)
   {
      this.id = id;
      this.label = label;
      this.URL = URL;
      this.date = date;
      this.user = user;
   }

}