package com.panorama.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Location implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "longitude")
   private java.lang.String longitude;
   @org.kie.api.definition.type.Label(value = "latitude")
   private java.lang.String latitude;
   @org.kie.api.definition.type.Label(value = "date")
   private java.lang.String date;
   @org.kie.api.definition.type.Label(value = "user")
   private com.panorama.common.User user;

   public Location()
   {
   }

   public java.lang.String getLongitude()
   {
      return this.longitude;
   }

   public void setLongitude(java.lang.String longitude)
   {
      this.longitude = longitude;
   }

   public java.lang.String getLatitude()
   {
      return this.latitude;
   }

   public void setLatitude(java.lang.String latitude)
   {
      this.latitude = latitude;
   }

   public java.lang.String getDate()
   {
      return this.date;
   }

   public void setDate(java.lang.String date)
   {
      this.date = date;
   }

   public com.panorama.common.User getUser()
   {
      return this.user;
   }

   public void setUser(com.panorama.common.User user)
   {
      this.user = user;
   }

   public Location(java.lang.String longitude, java.lang.String latitude,
         java.lang.String date, com.panorama.common.User user)
   {
      this.longitude = longitude;
      this.latitude = latitude;
      this.date = date;
      this.user = user;
   }

}