package com.panorama.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Originator implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "globalId")
   private java.lang.String globalId;
   @org.kie.api.definition.type.Label(value = "costCenterCode")
   private java.lang.String costCenterCode;
   @org.kie.api.definition.type.Label(value = "medium")
   private com.panorama.common.CodeValue medium;
   @org.kie.api.definition.type.Label(value = "channel")
   private com.panorama.common.CodeValue channel;
   @org.kie.api.definition.type.Label(value = "firstName")
   private java.lang.String firstName;
   @org.kie.api.definition.type.Label(value = "lastName")
   private java.lang.String lastName;
   @org.kie.api.definition.type.Label(value = "group")
   private com.panorama.common.CodeValue group;

   public Originator()
   {
   }

   public java.lang.String getGlobalId()
   {
      return this.globalId;
   }

   public void setGlobalId(java.lang.String globalId)
   {
      this.globalId = globalId;
   }

   public java.lang.String getCostCenterCode()
   {
      return this.costCenterCode;
   }

   public void setCostCenterCode(java.lang.String costCenterCode)
   {
      this.costCenterCode = costCenterCode;
   }

   public com.panorama.common.CodeValue getMedium()
   {
      return this.medium;
   }

   public void setMedium(com.panorama.common.CodeValue medium)
   {
      this.medium = medium;
   }

   public com.panorama.common.CodeValue getChannel()
   {
      return this.channel;
   }

   public void setChannel(com.panorama.common.CodeValue channel)
   {
      this.channel = channel;
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public com.panorama.common.CodeValue getGroup()
   {
      return this.group;
   }

   public void setGroup(com.panorama.common.CodeValue group)
   {
      this.group = group;
   }

   public Originator(java.lang.String globalId,
         java.lang.String costCenterCode,
         com.panorama.common.CodeValue medium,
         com.panorama.common.CodeValue channel, java.lang.String firstName,
         java.lang.String lastName, com.panorama.common.CodeValue group)
   {
      this.globalId = globalId;
      this.costCenterCode = costCenterCode;
      this.medium = medium;
      this.channel = channel;
      this.firstName = firstName;
      this.lastName = lastName;
      this.group = group;
   }

}