package com.panorama.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TransactionDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("type")
   private java.lang.String type;
   @org.kie.api.definition.type.Label("description")
   private java.lang.String description;
   @org.kie.api.definition.type.Label("posted")
   private java.lang.String posted;
   @org.kie.api.definition.type.Label("completed")
   private java.lang.String completed;

   @org.kie.api.definition.type.Label(value = "new_balance")
   private com.panorama.common.Money new_balance;

   @org.kie.api.definition.type.Label(value = "value")
   private com.panorama.common.Money value;

   public TransactionDetails()
   {
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.String getPosted()
   {
      return this.posted;
   }

   public void setPosted(java.lang.String posted)
   {
      this.posted = posted;
   }

   public java.lang.String getCompleted()
   {
      return this.completed;
   }

   public void setCompleted(java.lang.String completed)
   {
      this.completed = completed;
   }

   public com.panorama.common.Money getNew_balance()
   {
      return this.new_balance;
   }

   public void setNew_balance(com.panorama.common.Money new_balance)
   {
      this.new_balance = new_balance;
   }

   public com.panorama.common.Money getValue()
   {
      return this.value;
   }

   public void setValue(com.panorama.common.Money value)
   {
      this.value = value;
   }

   public TransactionDetails(java.lang.String type, java.lang.String description,
         java.lang.String posted, java.lang.String completed,
         com.panorama.common.Money new_balance, com.panorama.common.Money value)
   {
      this.type = type;
      this.description = description;
      this.posted = posted;
      this.completed = completed;
      this.new_balance = new_balance;
      this.value = value;
   }

}