package com.panorama.disputes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Attachment")
public class Attachment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("attachmentNumber")
   private java.lang.String attachmentNumber;
   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label("filePath")
   private java.lang.String filePath;
   @org.kie.api.definition.type.Label("fielName")
   private java.lang.String fileName;
   @org.kie.api.definition.type.Label("fileSize")
   private java.lang.String fileSize;
   @org.kie.api.definition.type.Label("docType")
   private java.lang.String docType;
   @org.kie.api.definition.type.Label("docTypeDescription")
   private java.lang.String docTypeDescription;
   @org.kie.api.definition.type.Label("archiveFlag")
   private java.lang.String archiveFlag;
   @org.kie.api.definition.type.Label("audit")
   private com.panorama.disputes.Audit audit;

   public Attachment()
   {
   }

   public java.lang.String getAttachmentNumber()
   {
      return this.attachmentNumber;
   }

   public void setAttachmentNumber(java.lang.String attachmentNumber)
   {
      this.attachmentNumber = attachmentNumber;
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getFilePath()
   {
      return this.filePath;
   }

   public void setFilePath(java.lang.String filePath)
   {
      this.filePath = filePath;
   }

   public java.lang.String getFileName()
   {
      return this.fileName;
   }

   public void setFileName(java.lang.String fileName)
   {
      this.fileName = fileName;
   }

   public java.lang.String getFileSize()
   {
      return this.fileSize;
   }

   public void setFileSize(java.lang.String fileSize)
   {
      this.fileSize = fileSize;
   }

   public java.lang.String getDocType()
   {
      return this.docType;
   }

   public void setDocType(java.lang.String docType)
   {
      this.docType = docType;
   }

   public java.lang.String getDocTypeDescription()
   {
      return this.docTypeDescription;
   }

   public void setDocTypeDescription(java.lang.String docTypeDescription)
   {
      this.docTypeDescription = docTypeDescription;
   }

   public java.lang.String getArchiveFlag()
   {
      return this.archiveFlag;
   }

   public void setArchiveFlag(java.lang.String archiveFlag)
   {
      this.archiveFlag = archiveFlag;
   }

   public com.panorama.disputes.Audit getAudit()
   {
      return this.audit;
   }

   public void setAudit(com.panorama.disputes.Audit audit)
   {
      this.audit = audit;
   }

   public Attachment(java.lang.String attachmentNumber,
         java.lang.String ticketNumber, java.lang.String filePath,
         java.lang.String fileName, java.lang.String fileSize,
         java.lang.String docType, java.lang.String docTypeDescription,
         java.lang.String archiveFlag, com.panorama.disputes.Audit audit)
   {
      this.attachmentNumber = attachmentNumber;
      this.ticketNumber = ticketNumber;
      this.filePath = filePath;
      this.fileName = fileName;
      this.fileSize = fileSize;
      this.docType = docType;
      this.docTypeDescription = docTypeDescription;
      this.archiveFlag = archiveFlag;
      this.audit = audit;
   }

}