package com.panorama.disputes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Attribute")
public class Attribute implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("attributeNumber")
   private java.lang.String attributeNumber;
   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label("attributeValue")
   private java.lang.String attributeValue;
   @org.kie.api.definition.type.Label("attributeName")
   private java.lang.String attributeName;

   public Attribute()
   {
   }

   public java.lang.String getAttributeNumber()
   {
      return this.attributeNumber;
   }

   public void setAttributeNumber(java.lang.String attributeNumber)
   {
      this.attributeNumber = attributeNumber;
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getAttributeValue()
   {
      return this.attributeValue;
   }

   public void setAttributeValue(java.lang.String attributeValue)
   {
      this.attributeValue = attributeValue;
   }

   public java.lang.String getAttributeName()
   {
      return this.attributeName;
   }

   public void setAttributeName(java.lang.String attributeName)
   {
      this.attributeName = attributeName;
   }

   public Attribute(java.lang.String attributeNumber,
         java.lang.String ticketNumber, java.lang.String attributeValue,
         java.lang.String attributeName)
   {
      this.attributeNumber = attributeNumber;
      this.ticketNumber = ticketNumber;
      this.attributeValue = attributeValue;
      this.attributeName = attributeName;
   }

}