package com.panorama.disputes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Classification")
public class Classification implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("accountNumber")
   private java.lang.String accountNumber;
   @org.kie.api.definition.type.Label("product")
   private com.panorama.disputes.CodeValue product;
   @org.kie.api.definition.type.Label("subProduct")
   private com.panorama.disputes.CodeValue subProduct;
   @org.kie.api.definition.type.Label("accountStatus")
   private com.panorama.disputes.CodeValue accountStatus;
   @org.kie.api.definition.type.Label("accountExtendedStatus")
   private com.panorama.disputes.CodeValue accountExtendedStatus;

   public Classification()
   {
   }

   public java.lang.String getAccountNumber()
   {
      return this.accountNumber;
   }

   public void setAccountNumber(java.lang.String accountNumber)
   {
      this.accountNumber = accountNumber;
   }

   public com.panorama.disputes.CodeValue getProduct()
   {
      return this.product;
   }

   public void setProduct(com.panorama.disputes.CodeValue product)
   {
      this.product = product;
   }

   public com.panorama.disputes.CodeValue getSubProduct()
   {
      return this.subProduct;
   }

   public void setSubProduct(com.panorama.disputes.CodeValue subProduct)
   {
      this.subProduct = subProduct;
   }

   public com.panorama.disputes.CodeValue getAccountStatus()
   {
      return this.accountStatus;
   }

   public void setAccountStatus(
         com.panorama.disputes.CodeValue accountStatus)
   {
      this.accountStatus = accountStatus;
   }

   public com.panorama.disputes.CodeValue getAccountExtendedStatus()
   {
      return this.accountExtendedStatus;
   }

   public void setAccountExtendedStatus(
         com.panorama.disputes.CodeValue accountExtendedStatus)
   {
      this.accountExtendedStatus = accountExtendedStatus;
   }

   public Classification(java.lang.String accountNumber,
         com.panorama.disputes.CodeValue product,
         com.panorama.disputes.CodeValue subProduct,
         com.panorama.disputes.CodeValue accountStatus,
         com.panorama.disputes.CodeValue accountExtendedStatus)
   {
      this.accountNumber = accountNumber;
      this.product = product;
      this.subProduct = subProduct;
      this.accountStatus = accountStatus;
      this.accountExtendedStatus = accountExtendedStatus;
   }

}