package com.panorama.disputes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Money")
public class Money implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "amount")
   private java.lang.Float amount;
   @org.kie.api.definition.type.Label(value = "currency")
   private java.lang.String currency;

   public Money()
   {
   }

   public java.lang.Float getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Float amount)
   {
      this.amount = amount;
   }

   public java.lang.String getCurrency()
   {
      return this.currency;
   }

   public void setCurrency(java.lang.String currency)
   {
      this.currency = currency;
   }

   public Money(java.lang.Float amount, java.lang.String currency)
   {
      this.amount = amount;
      this.currency = currency;
   }

}