package com.panorama.disputes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
@org.kie.api.definition.type.Label("Questionnaire")
public class Questionnaire implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("question")
   private java.lang.String question;
   @org.kie.api.definition.type.Label("nextQuestionCode")
   private java.lang.String nextQuestionCode;

   @org.kie.api.definition.type.Label("questionCode")
   private java.lang.String questionCode;

   @org.kie.api.definition.type.Label("answer")
   private java.lang.String answer;

   @org.kie.api.definition.type.Label("answerList")
   private java.lang.String answerList;

   @org.kie.api.definition.type.Label("questionLine2")
   private java.lang.String questionLine2;

   @org.kie.api.definition.type.Label("answerListLine2")
   private java.lang.String answerListLine2;

   public Questionnaire()
   {
   }

   public java.lang.String getQuestion()
   {
      return this.question;
   }

   public void setQuestion(java.lang.String question)
   {
      this.question = question;
   }

   public java.lang.String getNextQuestionCode()
   {
      return this.nextQuestionCode;
   }

   public void setNextQuestionCode(java.lang.String nextQuestionCode)
   {
      this.nextQuestionCode = nextQuestionCode;
   }

   public java.lang.String getQuestionCode()
   {
      return this.questionCode;
   }

   public void setQuestionCode(java.lang.String questionCode)
   {
      this.questionCode = questionCode;
   }

   public java.lang.String getAnswer()
   {
      return this.answer;
   }

   public void setAnswer(java.lang.String answer)
   {
      this.answer = answer;
   }

   public java.lang.String getAnswerList()
   {
      return this.answerList;
   }

   public void setAnswerList(java.lang.String answerList)
   {
      this.answerList = answerList;
   }

   public java.lang.String getQuestionLine2()
   {
      return this.questionLine2;
   }

   public void setQuestionLine2(java.lang.String questionLine2)
   {
      this.questionLine2 = questionLine2;
   }

   public java.lang.String getAnswerListLine2()
   {
      return this.answerListLine2;
   }

   public void setAnswerListLine2(java.lang.String answerListLine2)
   {
      this.answerListLine2 = answerListLine2;
   }

   public Questionnaire(java.lang.String question,
         java.lang.String nextQuestionCode, java.lang.String questionCode,
         java.lang.String answer, java.lang.String answerList,
         java.lang.String questionLine2, java.lang.String answerListLine2)
   {
      this.question = question;
      this.nextQuestionCode = nextQuestionCode;
      this.questionCode = questionCode;
      this.answer = answer;
      this.answerList = answerList;
      this.questionLine2 = questionLine2;
      this.answerListLine2 = answerListLine2;
   }

}