package com.panorama.disputes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Response")
public class Response implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("restType")
   private java.lang.String restType;
   @org.kie.api.definition.type.Label("dataType")
   private java.lang.String dataType;
   @org.kie.api.definition.type.Label("jsonBody")
   private java.lang.String jsonBody;

   public Response()
   {
   }

   public java.lang.String getRestType()
   {
      return this.restType;
   }

   public void setRestType(java.lang.String restType)
   {
      this.restType = restType;
   }

   public java.lang.String getDataType()
   {
      return this.dataType;
   }

   public void setDataType(java.lang.String dataType)
   {
      this.dataType = dataType;
   }

   public java.lang.String getJsonBody()
   {
      return this.jsonBody;
   }

   public void setJsonBody(java.lang.String jsonBody)
   {
      this.jsonBody = jsonBody;
   }

   public Response(java.lang.String restType, java.lang.String dataType,
         java.lang.String jsonBody)
   {
      this.restType = restType;
      this.dataType = dataType;
      this.jsonBody = jsonBody;
   }

}