package com.panorama.disputes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Tag")
public class Tag implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label("transactionNumber")
   private java.lang.String transactionNumber;
   @org.kie.api.definition.type.Label("value")
   private java.lang.String value;
   @org.kie.api.definition.type.Label("date")
   private java.lang.String date;

   @org.kie.api.definition.type.Label(value = "user")
   private com.panorama.disputes.User user;

   public Tag()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getTransactionNumber()
   {
      return this.transactionNumber;
   }

   public void setTransactionNumber(java.lang.String transactionNumber)
   {
      this.transactionNumber = transactionNumber;
   }

   public java.lang.String getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }

   public java.lang.String getDate()
   {
      return this.date;
   }

   public void setDate(java.lang.String date)
   {
      this.date = date;
   }

   public com.panorama.disputes.User getUser()
   {
      return this.user;
   }

   public void setUser(com.panorama.disputes.User user)
   {
      this.user = user;
   }

   public Tag(java.lang.String id, java.lang.String transactionNumber,
         java.lang.String value, java.lang.String date,
         com.panorama.disputes.User user)
   {
      this.id = id;
      this.transactionNumber = transactionNumber;
      this.value = value;
      this.date = date;
      this.user = user;
   }

}