package com.panorama.disputes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("TransactionMetadata")
public class TransactionMetadata implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("narrative")
   private java.lang.String narrative;
   @org.kie.api.definition.type.Label("comments")
   private java.util.List<com.panorama.disputes.Tag> comments;
   @org.kie.api.definition.type.Label("tags")
   private java.util.List<com.panorama.disputes.Tag> tags;

   @org.kie.api.definition.type.Label("where")
   private com.panorama.disputes.Location where;

   @org.kie.api.definition.type.Label(value = "images")
   private java.util.List<com.panorama.disputes.Image> images;

   public TransactionMetadata()
   {
   }

   public java.lang.String getNarrative()
   {
      return this.narrative;
   }

   public void setNarrative(java.lang.String narrative)
   {
      this.narrative = narrative;
   }

   public java.util.List<com.panorama.disputes.Tag> getComments()
   {
      return this.comments;
   }

   public void setComments(
         java.util.List<com.panorama.disputes.Tag> comments)
   {
      this.comments = comments;
   }

   public java.util.List<com.panorama.disputes.Tag> getTags()
   {
      return this.tags;
   }

   public void setTags(java.util.List<com.panorama.disputes.Tag> tags)
   {
      this.tags = tags;
   }

   public com.panorama.disputes.Location getWhere()
   {
      return this.where;
   }

   public void setWhere(com.panorama.disputes.Location where)
   {
      this.where = where;
   }

   public java.util.List<com.panorama.disputes.Image> getImages()
   {
      return this.images;
   }

   public void setImages(java.util.List<com.panorama.disputes.Image> images)
   {
      this.images = images;
   }

   public TransactionMetadata(java.lang.String narrative,
         java.util.List<com.panorama.disputes.Tag> comments,
         java.util.List<com.panorama.disputes.Tag> tags,
         com.panorama.disputes.Location where,
         java.util.List<com.panorama.disputes.Image> images)
   {
      this.narrative = narrative;
      this.comments = comments;
      this.tags = tags;
      this.where = where;
      this.images = images;
   }

}