package com.panorama.disputes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("TransactionOtherAccount")
public class TransactionOtherAccount implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label("bank_routing")
   private com.panorama.disputes.AccountRouting bank_routing;
   @org.kie.api.definition.type.Label("account_routing")
   private AccountRouting account_routing;
   @org.kie.api.definition.type.Label("holder")
   private com.panorama.disputes.Holder holder;
   @org.kie.api.definition.type.Label("metadata")
   private com.panorama.disputes.AccountMetadata metadata;

   @org.kie.api.definition.type.Label("accountRoutingAsString")
   private java.lang.String accountRoutingAsString;

   public TransactionOtherAccount()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public com.panorama.disputes.AccountRouting getBank_routing()
   {
      return this.bank_routing;
   }

   public void setBank_routing(
         com.panorama.disputes.AccountRouting bank_routing)
   {
      this.bank_routing = bank_routing;
   }

   public com.panorama.disputes.Holder getHolder()
   {
      return this.holder;
   }

   public void setHolder(com.panorama.disputes.Holder holder)
   {
      this.holder = holder;
   }

   public com.panorama.disputes.AccountMetadata getMetadata()
   {
      return this.metadata;
   }

   public void setMetadata(com.panorama.disputes.AccountMetadata metadata)
   {
      this.metadata = metadata;
   }

   public java.lang.String getAccountRoutingAsString()
   {
      return this.accountRoutingAsString;
   }

   public void setAccountRoutingAsString(java.lang.String accountRoutingAsString)
   {
      this.accountRoutingAsString = accountRoutingAsString;
   }

   public com.panorama.disputes.AccountRouting getAccount_routing()
   {
      return this.account_routing;
   }

   public void setAccount_routing(
         com.panorama.disputes.AccountRouting account_routing)
   {
      this.account_routing = account_routing;
   }

   public TransactionOtherAccount(java.lang.String id,
         com.panorama.disputes.AccountRouting bank_routing,
         com.panorama.disputes.AccountRouting account_routing,
         com.panorama.disputes.Holder holder,
         com.panorama.disputes.AccountMetadata metadata,
         java.lang.String accountRoutingAsString)
   {
      this.id = id;
      this.bank_routing = bank_routing;
      this.account_routing = account_routing;
      this.holder = holder;
      this.metadata = metadata;
      this.accountRoutingAsString = accountRoutingAsString;
   }

}