package com.panorama.disputes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("User")
public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label(value = "provider")
   private java.lang.String provider;
   @org.kie.api.definition.type.Label(value = "display_name")
   private java.lang.String display_name;

   public User()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getProvider()
   {
      return this.provider;
   }

   public void setProvider(java.lang.String provider)
   {
      this.provider = provider;
   }

   public java.lang.String getDisplay_name()
   {
      return this.display_name;
   }

   public void setDisplay_name(java.lang.String display_name)
   {
      this.display_name = display_name;
   }

   public User(java.lang.String id, java.lang.String provider,
         java.lang.String display_name)
   {
      this.id = id;
      this.provider = provider;
      this.display_name = display_name;
   }

}