package com.panorama.crosssale;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CrossSale implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CrossSale() {
    }

}