package panorama.panorama.crosssale;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public testObject() {
    }

}